### ISSUE TITLE
Mask not enforced

### ISSUE THREAD

**Issue by btecu** [ViniChab/supermask.js#2]
If you set a mask such as `99-9999` you can type three digits, change the cursor before the dash and type more digits ending up with something like `99999-9`.

**Comment by ViniChab** [comment]
Whoa, thanks for the issue kind sir
when you click out of the field, the field will reevaluate everything and remove anything that should not be there.
Although, I'll be fixing it soon enough.

**Comment by ViniChab** [comment]
The mask is now properly enforced
